project:
  type: website
  output-dir: docs
  
execute: 
  freeze: true

website:
  title: "Jingting Bai"
  description: The personal website of Ruorong Wang
  twitter-card: true
  open-graph: true
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Achievement.qmd
        text: Achievements
    right: 
      - icon: linkedin
        href: www.linkedin.com

format:
  html:
    theme: 
      light: spacelab
      dark: darkly
    
    css: styles.css
    toc: true

editor: visual

